variable:
  test_counter:
    value: 0
    attributes:
      icon: mdi:alarm

automation:
  - alias: test_counter
    initial_state: 'on'
    trigger:
      - platform: time
        seconds: '/1'
    action:
      - service: variable.set_variable
        data:
          variable: test_counter
          value: '{{ (variable.state | int) + 1 }}'
